[package]
name = "dragon-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
futures = "0.3.31"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
serenity = "0.12.2"
tokio = { version = "1.41.0", features = ["macros", "rt-multi-thread"] }
